name: Send Telegram Message Hourly

on:
  schedule:
    - cron: '0 */3 * * *'   # Every 3 hours on the hour
    - cron: '30 1/3 * * *'  # 1.5 hours offset from the previous run

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="пошли читать"
