name: Send Telegram Message Hourly

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.CHAT_ID }} \
            -d text="пошли читать"
